FROM python:3.11-slim

WORKDIR /app

# Instalar psycopg2 y requests
RUN pip install psycopg2-binary requests

# Copiar solo el script (no el CSV)
COPY scripts/populate_db.py .

# CMD por defecto (se puede sobrescribir)
CMD ["python", "populate_db.py"]
