version: "3.8"

services:
  postgres_db:
    image: postgres:12.7
    container_name: postgres_tp
    restart: unless-stopped
    environment:
      POSTGRES_USER: tp_user
      POSTGRES_PASSWORD: tp_password
      POSTGRES_DB: tp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/sql

volumes:
  postgres_data:
