CREATE TABLE denuncias_csv (
    fecha_ingreso        DATE,
    hora_ingreso         TIME,
    nro_registro_interno BIGINT PRIMARY KEY,
    situacion            TEXT,
    origen               TEXT,
    es_anonima           BOOLEAN,
    tema                 TEXT,
    subtema              TEXT,
    provincia            TEXT,
    localidad            TEXT,
    dependencia_alta     TEXT,
    via_ingreso          TEXT,
    derivacion_institucion TEXT,
    derivacion_fecha     TIMESTAMP,
    derivacion_judicializa BOOLEAN,
    derivacion2_institucion TEXT,
    derivacion2_fecha    TIMESTAMP,
    derivacion2_judicializa BOOLEAN,
    derivacion3_institucion TEXT,
    derivacion3_fecha    TIMESTAMP,
    derivacion3_judicializa BOOLEAN,
    denunciante_nacionalidad TEXT,
    denunciante_provincia TEXT,
    denunciante_localidad TEXT,
    denunciante_tipo      TEXT,
    denunciante_como_conocio_la_linea TEXT,
    denunciante_genero    TEXT,
    denunciante_edad_aparente INT,
    provincia_indec_id   INT
);
